#!/usr/bin/env bash
# WALLOC environment bootstrap.
#
# Pins the input / output directories, selects which GPUs to use, and
# (by default) installs Python dependencies. Writes a `.walloc_env`
# file at the repo root that you `source` to load the configuration:
#
#   bash setup.sh --train-input /kaggle/input/div2k \
#                 --test-input  /kaggle/input/kodak \
#                 --output      /kaggle/working/walloc \
#                 --gpus        0,1
#   source .walloc_env
#
# Then:
#   python scripts/train.py --dither_mode sd --lmbda 0.013
#   python scripts/run_gate.py --epochs 20
#
# Flags:
#   --train-input PATH    train image folder            (-> WALLOC_TRAIN_INPUT)
#   --test-input  PATH    test image folder             (-> WALLOC_TEST_INPUT)
#   --input PATH          shortcut: parent dir; scripts autodetect train/test
#   --output PATH         where checkpoints + tb logs go (-> WALLOC_OUTPUT_DIR)
#   --gpus LIST           '0,1' or single int '0' or 'all' or 'cpu'
#                         sets CUDA_VISIBLE_DEVICES + WALLOC_NUM_GPUS
#   --no-install          skip pip
#   --no-wandb            export WANDB_DISABLED=true (default already true)
#   --wandb               enable wandb if the package is installed
#   -h, --help            this message
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

TRAIN_INPUT=""
TEST_INPUT=""
INPUT_PARENT=""
OUTPUT_DIR=""
GPUS="all"
DO_INSTALL=1
WANDB="disabled"

usage() {
    sed -n '2,30p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
    exit 0
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --train-input)  TRAIN_INPUT="$2"; shift 2 ;;
        --test-input)   TEST_INPUT="$2";  shift 2 ;;
        --input)        INPUT_PARENT="$2"; shift 2 ;;
        --output)       OUTPUT_DIR="$2"; shift 2 ;;
        --gpus)         GPUS="$2"; shift 2 ;;
        --no-install)   DO_INSTALL=0; shift ;;
        --no-wandb)     WANDB="disabled"; shift ;;
        --wandb)        WANDB="enabled"; shift ;;
        -h|--help)      usage ;;
        *) echo "[setup.sh] unknown arg: $1" >&2; exit 2 ;;
    esac
done

# ---------- GPU selection ------------------------------------------------ #
case "$GPUS" in
    cpu)
        CUDA_LIST=""
        NUM_GPUS=0
        ;;
    all|auto|"")
        CUDA_LIST=""   # leave CUDA_VISIBLE_DEVICES unset
        NUM_GPUS=0     # 0 = auto in scripts
        ;;
    *)
        CUDA_LIST="$GPUS"
        NUM_GPUS=$(echo "$GPUS" | tr ',' '\n' | grep -c .)
        ;;
esac

# ---------- input path defaults ------------------------------------------ #
if [[ -z "$TRAIN_INPUT" && -n "$INPUT_PARENT" ]]; then
    TRAIN_INPUT="$INPUT_PARENT"
fi
if [[ -z "$TEST_INPUT" && -n "$INPUT_PARENT" ]]; then
    TEST_INPUT="$INPUT_PARENT"
fi

# Sanity-check provided paths (warn-only — autodetect will retry at runtime).
for var in TRAIN_INPUT TEST_INPUT OUTPUT_DIR; do
    val="${!var}"
    if [[ -n "$val" && "$var" != "OUTPUT_DIR" && ! -d "$val" ]]; then
        echo "[setup.sh] warning: $var=$val does not exist (yet)" >&2
    fi
done

if [[ -n "$OUTPUT_DIR" ]]; then
    mkdir -p "$OUTPUT_DIR"
fi

# ---------- python deps -------------------------------------------------- #
if [[ "$DO_INSTALL" -eq 1 ]]; then
    echo "[setup.sh] installing python deps"
    python -c "import sys; print('python', sys.version)"
    python -c "import torch; print('torch', torch.__version__, 'cuda', torch.cuda.is_available(), 'devices', torch.cuda.device_count())" \
        || echo "[setup.sh] torch not importable — install it before scripts"
    pip install -q --no-deps compressai==1.2.6 pytorch-msssim==1.0.0
    pip install -q geomloss==0.2.6 tqdm tensorboard
    python -c "import compressai; print('compressai', compressai.__version__)"
    python -c "from compressai.entropy_models import EntropyBottleneck; print('ok')"
    python -c "import geomloss; print('geomloss ok')"
    python -c "from torch.utils.tensorboard import SummaryWriter; print('tensorboard ok')"
fi

# ---------- emit .walloc_env --------------------------------------------- #
ENV_FILE="$REPO_ROOT/.walloc_env"
{
    echo "# generated by setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "export WALLOC_REPO_ROOT='$REPO_ROOT'"
    [[ -n "$TRAIN_INPUT" ]] && echo "export WALLOC_TRAIN_INPUT='$TRAIN_INPUT'"
    [[ -n "$TEST_INPUT"  ]] && echo "export WALLOC_TEST_INPUT='$TEST_INPUT'"
    [[ -n "$OUTPUT_DIR"  ]] && echo "export WALLOC_OUTPUT_DIR='$OUTPUT_DIR'"
    echo "export WALLOC_NUM_GPUS='$NUM_GPUS'"
    if [[ -n "$CUDA_LIST" ]]; then
        echo "export CUDA_VISIBLE_DEVICES='$CUDA_LIST'"
    elif [[ "$GPUS" == "cpu" ]]; then
        echo "export CUDA_VISIBLE_DEVICES=''"
    fi
    if [[ "$WANDB" == "disabled" ]]; then
        echo "export WANDB_DISABLED=true"
    else
        echo "unset WANDB_DISABLED"
    fi
    # PYTHONPATH so `from LTC...` and `from scripts...` work from any cwd
    echo "export PYTHONPATH='$REPO_ROOT:\${PYTHONPATH:-}'"
} > "$ENV_FILE"

echo
echo "[setup.sh] wrote $ENV_FILE"
cat "$ENV_FILE"
echo
echo "[setup.sh] next:  source $ENV_FILE"
